### ISSUE TITLE
Self-destruct 💣

### ISSUE THREAD

**Issue by dsamarin** [oftn-oswg/zerodrop#13]
Self-destruct is triggered by internal redirects to the special `"💣"` entry.

This will use secure wipe functionality to remove the following from the harddisk:
- The currently running binary and all symlinks found with [`os.Executable()`](https://tip.golang.org/pkg/os/#Executable)
- The configuration file
- The SQLite or MySQL databases listed in `config.DB.Source`
- Anything extra (files and directories) listed in `config.SelfDestruct`

This will be synchronized in a way that all currently connected clients will finish processing first.

**Comment by eligrey** [comment]
>This will be synchronized in a way that all currently connected clients will finish processing first.

I wouldn't do that, since then self-destruct would be vulnerable to slowloris-style DoS attacks. You should only try to ensure the payload for the entry that triggered the self-destruct is served, but even that can can be preempted if we pass some timeout.

**Comment by dsamarin** [comment]
> I wouldn't do that, since then self-destruct would be vulnerable to slowloris-style DoS attacks. You should only try to ensure the payload for the entry that triggered the self-destruct is served, but even that can can be preempted if we pass some timeout.

Okay, great. Had misunderstood.

Btw, other things to remove:
 - The directory specified in `config.UploadDirectory`
 - A Unix socket specified in `config.Listen`
