### ISSUE TITLE
Public pastebin-style

### ISSUE THREAD

**Issue by dsamarin** [oftn-oswg/zerodrop#14]
> Zerodrop instance with self-destruct disabled, public access to the list of entries, require the password for the clear all button, and implement localStorage/localForage-stored deletion tokens for deleting entries you created yourself

>  anyone can create entries, and entry creators can only delete their own entries

> with the admin password you can delete any entry or clear all entries

> clicking on delete for an entry you didn't create or clear all entries should bring up the admin login page if not logged in

**Comment by dsamarin** [comment]
This is basically done.
The only thing left to do now is implementing a configuration option to turn it **off**.

**Comment by eligrey** [comment]
Flashing ⚠️/🔗 emoji is a blocker for this.

**Comment by dsamarin** [comment]
Flashing complete
